name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: shaman-code
      - uses: actions/setup-python@v5
        with:
            python-version: '3.10'
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.12.0"
      - name: Install dependencies
        run: |
          cd shaman-code
          pip install -r docs/requirements.txt
      - name: Sphinx build
        run: |
          cd shaman-code
          script/build-docs.sh
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: shaman-code/docs/build/html
          force_orphan: true

